name: Laravel Tests

on:
  push:
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          extensions: mbstring, pdo, pdo_sqlite
          coverage: none

      - name: Copy .env
        run: cp .env.example .env

      - name: Install dependencies
        run: composer install --no-interaction --prefer-dist --optimize-autoloader

      - name: Generate app key
        run: php artisan key:generate

      - name: Install Passport keys
        run: php artisan passport:install --force

      - name: Run migrations & seed
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: memory
        run: php artisan migrate --seed

      - name: Run tests
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: memory
        run: php artisan test --parallel